export  const home= [
    {
        id:1,
        img: "/images/1.jpg",
        category:"Polkadot",
        time:"a Few seconds ago",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id:2,
        img: "/images/2.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id:3,
        img: "/images/3.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {   
        id:4,
        img: "/images/4.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id:5,
        img: "/images/5.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {   
        id:6,
        img: "/images/6.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {   
        id:7,
        img: "/images/7.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id:8,
        img: "/images/8.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
    {
        id:9,
        img: "/images/9.jpg",
        time:"a Few seconds ago",
        category:"Polkadot",
        title: "Heading",
        text: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab eius molestias, quasi, quam omnis magnam impedit hic totam repudiandae reiciendis voluptate inventore nisi quidem.",
    },
]
